# Build the latest SLE-12-SP3 image
FROM yastdevel/ruby:sle12-sp3

RUN zypper --non-interactive in --no-recommends \
  autoconf \
  automake \
  boost-devel \
  dbus-1-devel \
  docbook-xsl-stylesheets \
  e2fsprogs-devel \
  gcc-c++ \
  grep \
  libacl-devel \
  libbtrfs-devel \
  libmount-devel \
  libtool \
  libxml2-devel \
  libxslt \
  obs-service-source_validator \
  pam-devel \
  rpm-build \
  which

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
