#
# Makefile.repo for snapper
#

configure: all
	./configure

all:
	aclocal
	autoconf
	autoheader
	autoreconf --force --install

install: configure
	make
	make install

reconf: all
	./config.status --recheck
	./config.status
