#
# Makefile.repo for snapper
#

# somehow detect if this is a lib or lib64 system
LIB = $(shell gcc -v 2>&1 | sed -n 's,.*--libdir=/usr/\([^ ]*\).*,\1,p')
ifeq ($(LIB),)
LIB = lib
endif

PREFIX = /usr

configure: all
	./configure --prefix=$(PREFIX) --libdir=$(PREFIX)/$(LIB) --enable-selinux

all:
	aclocal
	autoconf
	autoheader
	autoreconf --force --install

install: configure
	make
	make install

reconf: all
	./config.status --recheck
	./config.status

