#!/bin/bash
set -e
set -u
#set -x

MYDIR=$(dirname $0)

runit() {
    local STRACE=""
    # STRACE="strace -efile"

    SNAPPER_ZYPP_PLUGIN_CONFIG=$MYDIR/zypp-plugin-invalid.conf \
      SNAPPER_ZYPP_PLUGIN_SNAPPER_CONFIG=testsuite \
      SNAPPER_ZYPP_PLUGIN_DBUS_SESSION=1 \
      DEBUG=1 \
      $STRACE \
      $MYDIR/../snapper-zypp-plugin
}

stomp_message() {
    local COMMAND="$1"
    local HEADERS="$2"
    local BODY="$3"
    printf '%s\n%s\n\n%s\0' "$COMMAND" "$HEADERS" "$BODY"
}


JSON='{
  "TransactionStepList": [
    {
      "type": "...",
      "stage": "...",
      "solvable": {
        "n": "mypackage"
      }
    }
  ]
}'

test_pre_post() {
    stomp_message PLUGINBEGIN "" ""
    stomp_message COMMITBEGIN "" "$JSON"
    stomp_message COMMITEND "" "$JSON"
    stomp_message PLUGINEND "" ""
}

setup() {
    :
}
teardown() {
    :
}

setup
test_pre_post | runit > /dev/null
teardown
