#!/bin/bash


function run()
{
    cmd=$1
    shift
    args=$*

    echo
    echo "*** running $cmd $args ***"
    echo

    ./$cmd $args

    if [ $? != 0 ] ; then
        echo "failed"
        exit 1
    fi
}


run simple1

run permissions1
run permissions2

run owner1
run owner2

