#!/bin/bash


function run()
{
    cmd=$1

    echo
    echo "*** running $cmd ***"
    echo

    ./$cmd

    if [ $? != 0 ] ; then
        echo "failed"
        exit 1
    fi
}


run sysconfig-get1

