#!/bin/sh

#
# paranoia settings
#
umask 022
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH


#
# get information from /etc/sysconfig
#
if [ -f /etc/sysconfig/snapper ] ; then
    . /etc/sysconfig/snapper
fi


#
# be nice
#
/usr/bin/renice -n 19 -p $$
/usr/bin/ionice -c 3 -p $$


#
# run snapper for all configs
#
for CONFIG in $SNAPPER_CONFIGS ; do

    NUMBER_CLEANUP="no"
    TIMELINE_CLEANUP="no"
    EMPTY_PRE_POST_CLEANUP="no"

    . /etc/snapper/configs/$CONFIG

    if [ "$NUMBER_CLEANUP" = "yes" ] ; then
	snapper --config=$CONFIG --quiet cleanup number
    fi

    if [ "$TIMELINE_CLEANUP" = "yes" ] ; then
	snapper --config=$CONFIG --quiet cleanup timeline
    fi

    if [ "$EMPTY_PRE_POST_CLEANUP" = "yes" ] ; then
	snapper --config=$CONFIG --quiet cleanup empty-pre-post
    fi

done

exit 0
