#!/bin/sh

#
# paranoia settings
#
umask 022
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH


#
# get information from /etc/sysconfig
#
if [ -f /etc/sysconfig/snapper ] ; then
    . /etc/sysconfig/snapper
fi


#
# run snapper for all configs
#
for CONFIG in $CONFIGS ; do

    TIMELINE_CREATE="no"

    . /etc/sysconfig/snapper.d/$CONFIG

    if [ "$TIMELINE_CREATE" = "yes" ] ; then
	snapper --config=$CONFIG create --description="timeline" --cleanup="timeline"
    fi

done

exit 0
