#!/bin/sh

#
# paranoia settings
#
umask 022
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH


#
# get information from /etc/sysconfig
#
if [ -f /etc/sysconfig/snapper ] ; then
    . /etc/sysconfig/snapper
fi


#
# run snapper for all configs
#
for CONFIG in $SNAPPER_CONFIGS ; do

    NUMBER_CLEANUP="no"
    TIMELINE_CLEANUP="no"

    . /etc/sysconfig/snapper.d/$CONFIG

    if [ "$NUMBER_CLEANUP" = "yes" ] ; then
	snapper --config=$CONFIG cleanup number
    fi

    if [ "$TIMELINE_CLEANUP" = "yes" ] ; then
	snapper --config=$CONFIG cleanup timeline
    fi

done

exit 0
